# Sample stellar.toml

#   The endpoint which clients should query to resolve stellar addresses
#   for users on your domain.
FEDERATION_SERVER="https://stellarid.io/federation/"

# asset with meta info
[[CURRENCIES]]
code="PIX"
issuer="GBT3C2YIJ7KMDOMZJDMKVRKCWMIADKYIOLCFEEVLZWPQYDCYYTO4COGC"
display_decimals=2
name="Pixel Asset"
desc="Revolutionizing the Art Industry"
conditions="21 million Total Supply"
image="https://justpixel.ga/img/logo.png"

# optional extra information for humans
# Useful place for anchors to detail various policies and required info

###################################
# Required compliance fields:
#      name=<recipient name>
#      addr=<recipient address>
# Federation Format:
#        <phone number>*anchor.com
#        Forwarding supported by sending to: forward*anchor.com
#           forward_type=bank_account
#           swift=<swift code of receiving bank>
#           acct=<recipient account number at receiving bank>
# Minimum Amount Forward: $2 USD
# Maximum Amount Forward: $10000 USD
